### ISSUE TITLE
[input-text] Could we have a space between * (asterixis) and label. 

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#50] opened 2021-04-05 10:24 UTC
**Describe the bug**
Could we please have a space between * (asterixis) and label. It is looking very close to each other. Please refer image below.

**To Reproduce**
On any input field, make it required. It is looking very close to each other. Please refer image below.

**Expected behavior**
Suggesting to have a space between * and label so that it doesn't look very near to each other and distinguish each other.

**Screenshots**
![spacingIssue](https://user-images.githubusercontent.com/72923647/113564530-2d219a80-9627-11eb-8d5a-97cff9c7b2cf.jpg)

Please revert if any more details are required.

**Comment by aweell** [comment] 2021-04-09 13:23
Thanks @ppurumala,

We add this feedback to consider into the review planned in our roadmap for the `input-text` component and for all text inputs or data inputs susceptible to being required.

**Comment by pwadhwani** [comment] 2021-05-25 13:19
Hi @aalbuerne @jsardid , Could you please provide updates on this ticket.

**Comment by aweell** [comment] 2021-05-25 14:04
Hello @pwadhwani, 

The draft of the input component review is planned to be available at the end of release 3.2.0, as can be seen in **the milestone witch the issue is linked**. 

After the release of the draft, the component still needs to be implemented. The guidelines from [Developer Central](https://developer.dxc.com/design/components/text-input) and the CDKs will be released simultaneously when this steps are completed.

**Comment by aweell** [comment] 2021-06-30 06:40
Hello @ppurumala,

Since we're working on new guidelines for the input component and the forms layout (both in draft status) the way we handle required and optional fields may change during this release. 

We don't plan to make any changes to the current inputs.

**Closed by aweell** 2021-06-30 06:40 UTC
Labels: component: input-text, status: under evaluation :mag_right:
